name: "🚀 Publish to GitHub Pages"

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  publish:
    name: "🚀 Publish"
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "🛎️ Checkout repository"
        uses: actions/checkout@v4

      - name: "🏗️ Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          registry-url: "https://registry.npmjs.org/"

      - name: "📦 Install dependencies"
        run: npm ci

      - name: "🛠️ Run build"
        run: npm run build
        env:
          VITE_APP_SEO_DESCRIPTION: ${{ vars.VITE_APP_SEO_DESCRIPTION }}
          VITE_APP_SEO_KEYWORDS: ${{ vars.VITE_APP_SEO_KEYWORDS }}
          VITE_APP_NAME: ${{ vars.VITE_APP_NAME }}
          VITE_APP_URL: ${{ vars.VITE_APP_URL }}
          VITE_APP_OG_IMAGE: ${{ vars.VITE_APP_OG_IMAGE }}

      - name: "🔍 Check build output"
        run: ls -la dist

      - name: "⚙️ Setup Pages"
        uses: actions/configure-pages@v5

      - name: "⬆️ Upload artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: "🚀 Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
